M48
; DRILL file {KiCad 9.0.6} date 2026-02-08T19:38:44+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-08T19:38:44+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X129.7Y-67.5
X129.7Y-72.5
T2
X93.92Y-65.25
X93.92Y-68.25
T3
X94.5Y-59.5
X95.0Y-94.0
X131.5Y-94.0
X132.0Y-59.5
M30
